apiVersion: v1
kind: ConfigMap
metadata:
  name: php-script
data:
  index.php: |
    <?php
      $x = 0.0001;
       for ($i = 0; $i <= 1000000; $i++) {
         $x += sqrt($x);
       }
      echo "OK!";
    ?>
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
  labels:
    app: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: php:5-apache
        volumeMounts:
        - name: config-volume
          mountPath: /var/www/html/
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
      volumes:
      - name: config-volume
        configMap:
          name: php-script

---

apiVersion: v1
kind: Service
metadata:
  name: php-service
spec:
  type: LoadBalancer
  selector:
    app: php
  ports: 
    - port: 80
---

